server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  application:
    name: WeKids-BE
  datasource:
    url: ${RDS_ENDPOINT}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  sql:
    init:
      mode: always
  jwt:
    secret: ${JWT_KEY}
    expiration:
      access: 2628000000
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: ${NAVER_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
cloud:
  aws:
    credentials:
      accessKey: ${S3_KEY}
      secretKey: ${S3_SECRET_KEY}
    s3:
      bucket: "wekids-s3"
    region:
      static: ap-northeast-2
    stack:
      auto: false

baas:
  id:
    baas-member-id: 1
    product-id: 5
  api:
    baas-url: ${BAAS_URL}